### ISSUE TITLE
Styling of password reset page

### ISSUE THREAD

**Issue by tommoor** [speak/speak.github.io#12]
Currently it sits on the same layout as the homepage. Something like this would be more appropriate:

https://www.sqwiggle.com/password/new

**Comment by ericbieller** [comment]
![image](https://cloud.githubusercontent.com/assets/740552/7547948/29b670da-f5ad-11e4-9f2b-9b36d0795d71.png)

**Comment by tommoor** [comment]
Looks great! I think we could say "new password" a lil less and friendly it up - I'd suggest:

## Reset your password

Almost there, choose a nice secure password below, you beautiful forgetful thing! 

- Your new password
- Confirm new password

"Save Password"
