### ISSUE TITLE
Add referrer to form

### ISSUE THREAD

**Issue by tommoor** [speak/speak.github.io#3]
It can be added to a hidden field via js, would be useful to know when folks signup from the blog etc

**Comment by ericbieller** [comment]
Looked into this and not too sure how to do it. Google uses a special ID to know how to handle the data:

```<input type="email" name="entry.981815137" placeholder="Enter your email" required>```

Did you have an idea of how we'd get the referrer from the form to the doc?

**Comment by tommoor** [comment]
Does the special ID change each time? Just need a little js to make document.referrer the value?

**Comment by ericbieller** [comment]
I believe you'd have to add another field in the google form itself. That's when the ID is generated, and that's how it knows which column to put it in methinks.

**Comment by tommoor** [comment]
That's cool if we can have a hidden field perhaps, not used google forms
enough to know if that's poss

On Fri, Mar 20, 2015 at 1:55 PM, Eric bieller <notifications@github.com>
wrote:

> I believe you'd have to add another field in the google form itself.
> That's when the ID is generated, and that's how it knows which column to
> put it in methinks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/speak/speak.github.io/issues/3#issuecomment-84142834>.
>



-- 
Tom Moor

http://tommoor.com
http://twitter.com/tommoor

**Comment by ericbieller** [comment]
Doesn't appear possible, closest answer I could find and it doesn't help https://productforums.google.com/forum/#!topic/docs/0TfmS3EGHFI

Closing for now
