### ISSUE TITLE
Add linux beta signup page

### ISSUE THREAD

**Issue by tommoor** [speak/speak.github.io#44]
- It should work exactly like Windows except go to a separate google form

**Comment by willbarrett** [comment]
Please also ask for distribution and window manager:

Distributions:
Arch
Debian
Fedora
Mint
Red Hat
Ubuntu
Other

Window Managers:
Cinnamon
Gnome
i3
KDE
Unity
XFCE
Other

I'll just shoot anyone with 'other' in either list an email.
