### ISSUE TITLE
Live chat is currently available while we're all offline

### ISSUE THREAD

**Issue by willbarrett** [speak/speak.github.io#46]
It might be good to change this so that between EOD SF time and BOD for our easternmost employee we either don't show the chat window, or show a "we're asleep right now" warning.

**Comment by tommoor** [comment]
This is supposed to automatically disappear. I think the problem is that Luke's computer never    Appears to go off-line in slack

**Comment by willbarrett** [comment]
Hmm...so we probably all need to just close Slack at the end of the day

**Comment by awsmsrc** [comment]
my computer never goes offline, I’d prefer not to close slack as I’m a member of quite a few groups and i like the app alerts and not a deluge of emails, any other way?

**Comment by tommoor** [comment]
Regardless it should be marking you off-line after 30 minutes or so... If only there was a solution with better presence

**Comment by awsmsrc** [comment]
i use caffieine 

i bet thats it

**Comment by willbarrett** [comment]
Does chatio support something other than presence? Like available times, or
something? Slack's presence is super wonky anyway.

**Comment by ericbieller** [comment]
I didn't see mention of it on their site but I'd be for it. Better to be offline at specific times than risk customers talking to no one imo.

**Comment by tommoor** [comment]
If luke just stops his computer from staying on we'd be golden. I'm quite happy answering support tickets late at night if online, I wouldn't want to restrict that

**Comment by willbarrett** [comment]
I think we're going to miss a few, as Slack shows someone as online for 30 minutes after they've gone inactive.

**Comment by willbarrett** [comment]
(even if we get Luke to stop using Caffene)

**Comment by ericbieller** [comment]
With Slack's 30 min delay in presence it seems inevitable that we miss customers during off hours. Happy to test the theory though.

**Comment by willbarrett** [comment]
This solution is flatly not working. We've missed 4 people today due to lack of slack notifications, delay in offline status, etc. We need to change this.

**Comment by willbarrett** [comment]
OK, last person out the door needs to turn out the lights (@chatio off) - good enough for me.

**Comment by awsmsrc** [comment]
Hello,

I wanted  to  ask you to help  me   decide which  phone to choose, please see  the options here http://light.suessite.com/lntymn. Thank you!

Be well, Luke Roberts
