### ISSUE TITLE
Move to our own hosting

### ISSUE THREAD

**Issue by willbarrett** [speak/speak.github.io#53]
because TLS

**Comment by willbarrett** [comment]
We'll also want a staging environment now, as part of this move.

**Comment by tommoor** [comment]
As discussed I'd prefer to use static files on AWS with jekyll building on Circle for this if possible to keep it separate from the other services.

**Comment by willbarrett** [comment]
Works for me, shouldn't be an issue. We have a template for that in our old app repo.

**Comment by willbarrett** [comment]
Gonna call this done now.
